### ISSUE TITLE
Adding 3rd Party Libraries and typescript

### ISSUE THREAD

**Issue by alfredoperez** [spboyer/cleanshave#13]
What are the steps to add a 3rd party libraries? 
I was trying to add https://www.npmjs.com/package/ng2-bootstrap

How would you automatically compile TS?

**Comment by spboyer** [comment]
After you instal the ng2-bootstrap, run `typings install` and check the **/Typings** folder to see if the related *.d.ts file is there for ng2-bootstrap.

For building the TS, there is a gulp task `build-prod` that would handle that, for dev be sure to add the dependencies in the html and in the gulp file like the other javascript files
