### ISSUE TITLE
How to open this project in VS 2015

### ISSUE THREAD

**Issue by titobf** [spboyer/cleanshave#6]
I'm wondering how to open this project in VS 2015. I suppose I will need to create a new project and drop all these files inside it, right? Thanks.

**Comment by spboyer** [comment]
To open in VS you need to open using the git connector.

<img width="392" alt="screen shot 2015-11-21 at 8 46 44 am" src="https://cloud.githubusercontent.com/assets/7681382/11319010/828bae9a-9036-11e5-8e8e-fa09533e5db6.png">

Then open the `project.json` file. Be sure to have the **ASPNET 5** file/project type selected.

<img width="924" alt="screen shot 2015-11-21 at 8 47 23 am" src="https://cloud.githubusercontent.com/assets/7681382/11319012/a6cdbbfe-9036-11e5-9ff9-6f4fc91f90a8.png">

get the latest push of the code, I had to add a `Before Build` step to have the gulp tasks run and build/compile the typescript and angular 2 project portions if you are just going to F5.

**Comment by titobf** [comment]
Thank you! I didn't know about opening the project by using the project.json file.
