### ISSUE TITLE
Support for angular 2 beta?

### ISSUE THREAD

**Issue by gxclarke** [spboyer/cleanshave#9]
Great project! Are you planning to upgrade it to use the Angular 2 beta? I've been trying to do it myself,  but no success so far. The syntax changes seem to be substantial.

**Comment by michalstepien** [comment]
+1

**Comment by spboyer** [comment]
It is on the radar.  There are some supporting libraries that need upgrading or are moving very fast, also with aspnet 5 now aspnetCore; I may wait till RC2 to make all of the changes.

**Comment by maleet** [comment]
+1

**Comment by spboyer** [comment]
This has been updated for angular2-beta9
